/*
 * # Module: azure/resource-groups
 *
 * Creates one or more Azure Resource Groups from a map of definitions.
 *
 * The Resource Group names are generated by prefixing each key with
 * `var.resource_name_prefix` (default `rg`)
 */
 
resource "azurerm_resource_group" "this" {
  for_each = var.resource_groups

  # Required attributes
  name = format(
    "%s-%s",
    var.resource_name_prefix,
    each.key
  )
  location = each.value.location

  # Optional attributes
  tags = merge(
    var.general_tags,
    each.value.tags
  )
}