/*
 * # Module: azure/storage-accounts
 *
 * Creates one or more of the following Azure Storage Account resources from a map of definitions:
 *
 * - Azure Storage Account
 * - Azure Storage Account Static Website
 * - Azure Storage Container
 *
 * The Storage Account names are generated by subfixing each 'name' property with
 * `random_integer` (default length `4`)
 */

resource "random_integer" "storage_account" {
  for_each = var.storage_accounts

  # Required attributes
  min = var.random_integer.min
  max = var.random_integer.max

  keepers = {
    ran_int = each.key
  }
}

resource "azurerm_storage_account" "this" {
  for_each = var.storage_accounts

  # Required attributes
  name = format(
    "%s%s",
    each.value.name,
    random_integer.storage_account[each.key].result
  )
  resource_group_name      = var.resource_groups[each.value.resource_group_key].name
  location                 = var.resource_groups[each.value.resource_group_key].location
  account_tier             = each.value.account_tier
  account_replication_type = each.value.account_replication_type

  # Optional attributes
  account_kind = each.value.account_kind
  access_tier = contains(
    ["BlobStorage", "FileStorage", "StorageV2"],
    each.value.account_kind
  ) ? each.value.access_tier : null
  blob_properties {
    versioning_enabled = each.value.blob_properties.versioning_enabled
  }
  tags = merge(
    var.general_tags,
    each.value.tags
  )

  # Address checkov issues
  shared_access_key_enabled       = false # Disable Shared Key authorization
  allow_nested_items_to_be_public = false # Ensure storage account is configured without blob anonymous access and restricted from public access
  local_user_enabled              = false # Disable local users

  # checkov:skip=CKV_AZURE_33:Queue service is not used in this project.
  # checkov:skip=CKV_AZURE_59:Public access to storage accounts is needed.
  # checkov:skip=CKV_AZURE_206:Project uses LRS as replication type as files are easily re-generatable. ZRS/GRS solution is an overkill.
  # checkov:skip=CKV2_AZURE_1:CMKs would require an Azure Key Vault resource which has been decided not to provision. Reference ADR #0007.
  # checkov:skip=CKV2_AZURE_33:Private Endpoints require an Azure Virtual Network and Azure Private DNS Zone resources which are not used as part of this project.  
}

resource "azurerm_storage_account_static_website" "this" {
  for_each = var.storage_account_static_websites

  # Required attributes
  storage_account_id = azurerm_storage_account.this[each.value.storage_account_key].id

  # Optional attributes
  index_document     = each.value.index_document
  error_404_document = each.value.error_404_document
}

resource "azurerm_storage_container" "this" {
  for_each = var.storage_account_containers

  # Required attributes
  name                  = each.value.name
  storage_account_id    = azurerm_storage_account.this[each.value.storage_account_key].id
  container_access_type = each.value.container_access_type

  # Address checkov issues
  # checkov:skip=CKV2_AZURE_21:Would require provision of log analytics workspace and log analytics storage insights resources to satisfy. Those are disproportionate to project's scope.
}