/*
 * # Module: azure/service-plans
 *
 * Creates one or more Azure Service Plans from a map of definitions.
 *
 * The Resource Group names are generated by prefixing each 'name' property with
 * `var.resource_name_prefix` (default `sp`) followed by `random_integer` (default length `4`)
 */

resource "random_integer" "service_plan" {
  for_each = var.service_plans

  # Required attributes
  min = var.random_integer.min
  max = var.random_integer.max

  keepers = {
    ran_int = each.key
  }
}

resource "azurerm_service_plan" "this" {
  for_each = var.service_plans

  # Required attributes
  name = format(
    "%s-%s-%s",
    var.resource_name_prefix,
    each.value.name,
    random_integer.service_plan[each.key].result
  )
  resource_group_name = var.resource_groups[each.value.resource_group_key].name
  location            = var.resource_groups[each.value.resource_group_key].location
  os_type             = each.value.os_type
  sku_name            = each.value.sku_name

  # Optional attributes
  tags = merge(
    var.general_tags,
    each.value.tags
  )

  # Address checkov issues
  # checkov:skip=CKV_AZURE_212:Project uses the Flex Consumption plan as traffic is expected to be low. Multi-instance solution is not required.
  # checkov:skip=CKV_AZURE_225:Project uses the Flex Consumption plan as traffic is expected to be low. Zone reduntant solution is not required.
}