name: Test pre workflow

on:
  workflow_dispatch:

jobs:
  test_job_one:
    runs-on: ubuntu-latest

    steps:
      - name: Test Job One
        run: |          
          echo "Job one"
          
  test_job_two:
    runs-on: ubuntu-latest

    steps:
      - name: Test Job Two
        run: |          
          echo "Job Two"
