name: Test workflow

on:
  workflow_run:
    workflows:
      - "Test pre workflow"
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test workflow
        run: |
          echo "Workflow: ${{ github.event.workflow_run.name }}"
          echo "Conclusion: ${{ github.event.workflow_run.conclusion }}"
          echo "Event: ${{ github.event.workflow_run.event }}"
          echo "Branch: ${{ github.event.workflow_run.head_branch }}"
          echo "SHA: ${{ github.event.workflow_run.head_sha }}"
