name: Upload Backend Files to Azure

on:
  # Dispatch for testing purposes
  workflow_dispatch:
  push:
    branches: 
      - main
    paths: 
      - "backend/api/**"

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id:       ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id:       ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.15.7"
      
      - name: Terraform Init
        working-directory: ./infrastructure/terraform
        run: terraform init -input=false

      - name: Get Resource Group Name From Terraform
        working-directory: ./infrastructure/terraform
        run: |
          resource_group_name=$(terraform output -json resource_groups | jq -r ".cloudresumechallenge.name")
          echo "RESOURCE_GROUP_NAME=$resource_group_name" >> $GITHUB_ENV

      - name: Get Function App Name From Terraform
        working-directory: ./infrastructure/terraform
        run: |
          function_app_name=$(terraform output -json function_apps_flex | jq -r ".backend.name")
          echo "FUNCTION_APP_NAME=$function_app_name" >> $GITHUB_ENV

      - name: Zip the Deployment Files
        working-directory: ./backend/api
        run: |
          zip -r ../deployment.zip . -x \
          tests/* \
          requirements-test.txt \
          .funcignore \
          pytest.ini
      
      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az functionapp deployment source config-zip \
            --resource-group $RESOURCE_GROUP_NAME \
            --name $FUNCTION_APP_NAME \
            --src-path "./backend/deployment.zip" \
            --build-remote true
