name: Terraform vulnerability scan

on:
  pull_request:
    branches:
      - main
    paths:
      - "infrastructure/terraform/**/*.tf"

permissions:
  id-token: write
  contents: read
  
jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      TF_VAR_cloudflare_zone_id: ${{ secrets.CLOUDFLARE_ZONE_ID }}

    defaults:
      run:
        working-directory: ./infrastructure/terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id:       ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id:       ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.15.7"
     
      - name: Terraform Init
        run: terraform init -input=false
          
      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false -out=deploy.tfplan

      - name: Convert plan to JSON
        run: terraform show -json deploy.tfplan > checkov.json

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          file: infrastructure/terraform/checkov.json
          framework: terraform_plan
          repo_root_for_plan_enrichment: infrastructure/terraform          
