name: Upload Frontend Files to Azure

on:
  # Workflow dispatch for testing purposes
  workflow_dispatch:
  push:
    branches: 
      - main
    paths: 
      - "frontend/**"

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infrastructure/terraform
    outputs:
      RESOURCE_GROUP_NAME: ${{ steps.extract.outputs.RESOURCE_GROUP_NAME }}
      STORAGE_ACCOUNT_NAME: ${{ steps.extract.outputs.STORAGE_ACCOUNT_NAME }}
      AFD_PROFILE_NAME: ${{ steps.extract.outputs.AFD_PROFILE_NAME }}
      AFD_ENDPOINT_NAME: ${{ steps.extract.outputs.AFD_ENDPOINT_NAME }}
      AFD_DOMAIN: ${{ steps.extract.outputs.AFD_DOMAIN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id:       ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id:       ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.15.7"
      
      - name: Terraform Init
        run: terraform init -input=false

      - name: Extract Terraform outputs
        id: extract
        run: |     
          echo "RESOURCE_GROUP_NAME=$(terraform output -json resource_groups | jq -r ".cloudresumechallenge.name")" >> $GITHUB_OUTPUT 
          echo "STORAGE_ACCOUNT_NAME=$(terraform output -json storage_accounts | jq -r ".frontend.name")" >> $GITHUB_OUTPUT
          echo "AFD_PROFILE_NAME=$(terraform output -json frontdoor_profiles | jq -r ".cloudresumechallenge.name")" >> $GITHUB_OUTPUT
          echo "AFD_ENDPOINT_NAME=$(terraform output -json frontdoor_endpoints | jq -r ".cloudresumechallenge.name")" >> $GITHUB_OUTPUT
          echo "AFD_DOMAIN=$(terraform output -json frontdoor_custom_domains | jq -r ".cloudresumechallenge.domain")" >> $GITHUB_OUTPUT

  upload-frontend:
    needs: terraform
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id:       ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id:       ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Sync Frontend to Azure
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az storage blob sync \
            --account-name ${{ needs.terraform.outputs.STORAGE_ACCOUNT_NAME }} \
            --container '$web' \
            --source ./frontend \
            --auth-mode login
  
  cache-purge:
    needs: [terraform, upload-frontend]
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id:       ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id:       ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Purge AFD Cache
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az afd endpoint purge \
            --resource-group ${{ needs.terraform.outputs.RESOURCE_GROUP_NAME }} \
            --profile-name ${{ needs.terraform.outputs.AFD_PROFILE_NAME }} \
            --endpoint-name ${{ needs.terraform.outputs.AFD_ENDPOINT_NAME }} \
            --domains ${{ needs.terraform.outputs.AFD_DOMAIN }} \
            --content-paths '/*'

