name: Generate terraform docs
on:
  pull_request:
    paths:
      - 'infrastructure/terraform/**/*.tf'

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Generate docs for root module and submodules
        uses: terraform-docs/gh-actions@main
        with:
          find-dir: infrastructure/terraform
          config-file: infrastructure/terraform/.terraform-docs.yml
          output-file: README.md
          output-method: inject
          git-push: "true"
