name: Generate terraform docs

on:
  push:
    branches:
      - terraform
    paths:
      - "infrastructure/terraform/**/*.tf"

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: terraform

      - name: Generate Terraform documentation
        uses: terraform-docs/gh-actions@v1.4.1
        with:
          find-dir: infrastructure/terraform
          config-file: .terraform-docs.yml
          git-push: true
